---
- name: Install Filebeat
  apt:
    name: filebeat
    state: present

- name: Configure Filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0640'
  notify: restart filebeat

- name: Enable nginx module
  command: filebeat modules enable nginx
  args:
    creates: /etc/filebeat/modules.d/nginx.yml

- name: Configure nginx module
  template:
    src: nginx.yml.j2
    dest: /etc/filebeat/modules.d/nginx.yml
    owner: root
    group: root
    mode: '0640'
  notify: restart filebeat

- name: Setup Filebeat index template
  command: filebeat setup --index-management
  args:
    creates: /var/lib/filebeat/.index_management_done

- name: Ensure Filebeat is started and enabled
  service:
    name: filebeat
    state: started
    enabled: yes