---
# Global variables
ansible_user: safalkon
ansible_ssh_private_key_file: "/home/safalkon/.ssh/id_ed25519"
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o IdentitiesOnly=yes'

# Environment
project_name: diplom

# Zabbix
zabbix_server_ip: "zabbix.ru-central1.internal"
zabbix_db_password: "ChangeMe123"
zabbix_admin_user: Admin
zabbix_admin_password: zabbix

# Elasticsearch
elasticsearch_host: "elasticsearch.ru-central1.internal"
elasticsearch_cluster_name: "diplom-cluster"
elasticsearch_username: elastic
elasticsearch_password: "ChangeMe123"

# Kibana
kibana_system_password: "ChangeMe123"
kibana_encryption_key: "changemechangemechangemechangeme"

# Filebeat
filebeat_elasticsearch_host: "elasticsearch.ru-central1.internal"

# Backup
s3_access_key: ""
s3_secret_key: ""
s3_bucket: "backup-bucket"
s3_endpoint: "https://storage.yandexcloud.net"